@host = http://localhost:3001
@userId = ea69b6cb-011c-416e-beec-cd3b71aee9e0

### Health
GET {{host}}/health

###

### Get users
GET {{host}}/users

###

### Create user
POST {{host}}/users
Content-Type: application/json

{
  "email": "ivan@example.com",
  "name": "Duplicate Test"
}

### Update user
PATCH {{host}}/users/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "name": "Ghost User"
}

### Delete user
DELETE {{host}}/users/{{userId}}